- name: Create Awesome Badge
  uses: schneegans/dynamic-badges-action@v1.0.0
  with:
    auth: ${{ secrets.GIST_SECRET }}
    gistID: gist:6e1b5f4f4259301c69e46f70cab4ed88
    filename: git-badges.json
    label: Hello
    message: World
    color: orange
